services:
  - type: web
    name: impostor-bot-web
    env: node
    buildCommand: "npm install"
    startCommand: "npm run start:web"
    autoDeploy: true
    plan: free
    routes:
      - type: http
        path: /
        healthCheckPath: /health
       envVars:
      - key: DISCORD_TOKEN
